name: Auto Deploy NodeApplication on ec2

on:
  push:
    branches:
      - main  # This triggers deployment when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on a Linux-based GitHub runner (Ubuntu)

    steps:
      # Step 1: Checkout the latest code from the GitHub repository
      - name: Checkout Source
        uses: actions/checkout@v4  # Pulls the latest code from GitHub

      # Step 2: Login to Docker Hub using credentials stored in GitHub secrets
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  # Log into Docker Hub

      # Step 3: Build the Docker image from the project
      - name: Build Docker Image
        run: docker build -t shafique471/node_aws .  # Build the Docker image with the tag 'shafique471/node_aws'

      # Step 4: Push the built Docker image to Docker Hub
      - name: Publish Image to Docker Hub
        run: docker push shafique471/node_aws:latest  # Push the image to Docker Hub with the 'latest' tag

  deploy:
    needs: build  # This job will run after the 'build' job is successful
    runs-on: self-hosted  # Run the deploy job on a self-hosted runner (EC2 or other server)

    steps:
      # Step 1: Pull the latest Docker image from Docker Hub
      - name: Pull Image from Docker Hub
        run: docker pull shafique471/node_aws:latest  # Pull the image with the 'latest' tag from Docker Hub

      # Step 2: Remove any existing container with the same name before running a new one (if any)
      - name: Remove Old Container (if exists)
        run: docker rm -f nodejs-app-container || true  # Force-remove any old container named 'nodejs-app-container' if it exists

      # Step 3: Run the new Docker container using the pulled image with all necessary environment variables
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 \
            --name nodejs-app-container \
            -e PORT=${{ secrets.PORT }} \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
            shafique471/node_aws
